name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.18]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out the repository code

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # Action to set up Node.js
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Lint
      run: npm run lint